# Generated by Django 3.1.4 on 2021-02-04 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_notes_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='owner',
        ),
        migrations.AddField(
            model_name='notes',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes_owner', to='users.user'),
            preserve_default=False,
        ),
    ]
