# Generated by Django 3.1.4 on 2021-02-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_remove_group_notes'),
        ('notes', '0004_auto_20210204_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='groups',
            field=models.ManyToManyField(related_name='notes_groups', to='groups.Group'),
        ),
    ]
