# Generated by Django 3.1.4 on 2021-02-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20210204_1117'),
        ('groups', '0002_auto_20210204_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='notes',
            field=models.ManyToManyField(related_name='group_notes', to='notes.Notes'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
