# Generated by Django 3.1.4 on 2021-02-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20210204_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='notes',
        ),
    ]
